import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Settings, X } from 'lucide-react';
import { useState } from 'react';
export default function SettingsPanel({ settings, onUpdateSettings, }) {
    const [isOpen, setIsOpen] = useState(false);
    if (!isOpen) {
        return (_jsx("button", { onClick: () => setIsOpen(true), className: "p-2 text-gray-300 hover:bg-gray-700 rounded-lg transition-colors", title: "Settings", children: _jsx(Settings, { size: 18 }) }));
    }
    return (_jsx("div", { className: "fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50", children: _jsxs("div", { className: "bg-gray-800 rounded-lg border border-gray-700 p-6 max-w-md w-full mx-4", children: [_jsxs("div", { className: "flex items-center justify-between mb-6", children: [_jsx("h2", { className: "text-xl font-bold text-white", children: "Settings" }), _jsx("button", { onClick: () => setIsOpen(false), className: "p-1 hover:bg-gray-700 rounded-lg transition-colors", children: _jsx(X, { size: 20 }) })] }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { children: [_jsxs("label", { className: "block text-gray-300 text-sm font-medium mb-2", children: ["Font Size: ", settings.fontSize, "px"] }), _jsx("input", { type: "range", min: "10", max: "20", value: settings.fontSize, onChange: (e) => onUpdateSettings({ fontSize: parseInt(e.target.value) }), className: "w-full" })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-gray-300 text-sm font-medium mb-2", children: "Theme" }), _jsxs("select", { value: settings.theme, onChange: (e) => onUpdateSettings({
                                        theme: e.target.value,
                                    }), className: "w-full px-3 py-2 bg-gray-700 text-white border border-gray-600 rounded-lg", children: [_jsx("option", { value: "dark", children: "Dark" }), _jsx("option", { value: "light", children: "Light" })] })] }), _jsxs("div", { className: "flex items-center", children: [_jsx("input", { type: "checkbox", id: "autoFormat", checked: settings.autoFormat, onChange: (e) => onUpdateSettings({ autoFormat: e.target.checked }), className: "w-4 h-4 rounded" }), _jsx("label", { htmlFor: "autoFormat", className: "ml-3 text-gray-300 text-sm", children: "Auto Format on Save" })] }), _jsxs("div", { className: "flex items-center", children: [_jsx("input", { type: "checkbox", id: "lineNumbers", checked: settings.showLineNumbers, onChange: (e) => onUpdateSettings({ showLineNumbers: e.target.checked }), className: "w-4 h-4 rounded" }), _jsx("label", { htmlFor: "lineNumbers", className: "ml-3 text-gray-300 text-sm", children: "Show Line Numbers" })] })] }), _jsx("button", { onClick: () => setIsOpen(false), className: "mt-6 w-full px-4 py-2 bg-secondary text-white rounded-lg hover:bg-blue-600 transition-colors", children: "Close" })] }) }));
}
